title: Another helloworld jeckyll website
author: Ginger Elve, yu \m/
email: no-ne-of-your-business@domain.com
description: > # this means to ignore newlines until "baseurl:"
  customized meta descriprion.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
